stages:
- name: test
  if: branch != master AND type = push AND tag is blank
- name: npm
  if: branch = master AND type = push AND tag is blank
- name: github
  if: branch = master AND type = push AND tag is blank

jobs:
  include:
  - stage: test
    language: node_js
    node_js:
      - lts/*
    dist: xenial
    install:
      - npm i
    script:
      - npm run build
      - npm test
      - npm run lint
  - stage: npm
    language: node_js
    node_js:
      - lts/*
    dist: xenial
    install:
      - npm i
    script:
      - npm run build
    deploy:
      provider: npm
      email: npm@parasrah.com
      skip_cleanup: true
  - stage: github
    language: node_js
    node_js:
      - lts/*
    dist: xenial
    install: npm i
    script: npm run build
    before_deploy:
      - export TRAVIS_TAG=$(npm run version | tail -n1)
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      file_glob: true
      file: dist/*
      skip_cleanup: true
